import { authConfigured, supabase, signInGoogle, signInEmail, signOut } from './supabase.js';
import { initStore, activeUser, setActiveUser } from './progress-store.js';
import { mountGreek } from './greek-deck.js';
import { mountLatin } from './latin-deck.js';
let greekMounted=false,latinMounted=false;
const $=s=>document.querySelector(s);
function route(){const hash=(location.hash||'#home').slice(1);document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const page=document.querySelector('#page-'+(hash==='greek'||hash==='latin'?hash:'home'));page.classList.add('active');if(hash==='greek'&&!greekMounted){greekMounted=true;mountGreek($('#greekMount')).catch(e=>$('#greekMount').innerHTML=`<div class="notice">${e.message}</div>`)}if(hash==='latin'&&!latinMounted){latinMounted=true;mountLatin($('#latinMount')).catch(e=>$('#latinMount').innerHTML=`<div class="notice">${e.message}</div>`)}window.scrollTo({top:0,behavior:'instant'})}
function userUI(){const u=activeUser(),label=$('#userLabel'),btn=$('#accountBtn');if(u){label.textContent=u.email||u.user_metadata?.full_name||'Signed in';btn.textContent='Account';$('#homeAuthTitle').textContent='Your progress is synced';$('#homeAuthText').textContent='Your Greek and Latin study state is stored with your account and can be resumed on another device.';$('#homeSignIn').textContent='Account';}else{label.textContent='Guest';btn.textContent='Sign in';$('#homeAuthTitle').textContent='Study as a guest';$('#homeAuthText').textContent='Guest progress stays on this browser. Sign in to sync progress across devices.';$('#homeSignIn').textContent='Sign in to sync';}}
function openAuth(){const u=activeUser();$('#authModal').classList.remove('hidden');$('#authConfigured').classList.toggle('hidden',!authConfigured||!!u);$('#authNotConfigured').classList.toggle('hidden',authConfigured||!!u);$('#signedInPanel').classList.toggle('hidden',!u);if(u)$('#signedInEmail').textContent=u.email||'your account';$('#authStatus').textContent=''}
function closeAuth(){$('#authModal').classList.add('hidden')}
window.addEventListener('hashchange',route);$('#accountBtn').addEventListener('click',openAuth);$('#homeSignIn').addEventListener('click',openAuth);$('#closeAuth').addEventListener('click',closeAuth);$('#authModal').addEventListener('click',e=>{if(e.target.id==='authModal')closeAuth()});$('#googleSignIn').addEventListener('click',async()=>{try{$('#authStatus').textContent='Opening Google sign-in…';await signInGoogle()}catch(e){$('#authStatus').textContent=e.message}});$('#emailForm').addEventListener('submit',async e=>{e.preventDefault();try{await signInEmail($('#emailInput').value.trim());$('#authStatus').textContent='Check your email for the sign-in link.'}catch(err){$('#authStatus').textContent=err.message}});$('#signOutBtn').addEventListener('click',async()=>{await signOut();location.reload()});
const u=await initStore();userUI();route();
if(supabase){supabase.auth.onAuthStateChange((_event,session)=>{const before=activeUser()?.id||null,after=session?.user?.id||null;if(before!==after){setActiveUser(session?.user||null);location.reload()}})}
