import { GREEK_CARDS } from '../data/greek-cards.js';
import { loadProgress, saveProgress } from './progress-store.js';
const DECK='greek-i-v1';
const fresh=()=>({version:1,stats:Object.fromEntries(GREEK_CARDS.map(c=>[c.id,{seen:0,right:0,wrong:0,easy:0,medium:0,hard:0,last:-999}])),answered:0,current:null,filter:'all',history:[]});
let state=null,root=null,revealed=false,result=null,diff=null;
function norm(s){const f=fresh();if(!s||!s.stats)return f;for(const c of GREEK_CARDS)if(!s.stats[c.id])s.stats[c.id]=f.stats[c.id];return {...f,...s,stats:s.stats};}
function pool(){return GREEK_CARDS.filter(c=>state.filter==='all'||c.category===state.filter)}
function weight(c){const s=state.stats[c.id];let w=1+s.wrong*3+s.hard*2+s.medium*.55-s.easy*.18-s.right*.08;const since=state.answered-s.last;if(since<=1)w*=.08;else if(since<=3)w*=.3;else if(since<=6)w*=.7;return Math.max(.35,w)}
function pick(){const p=pool();if(!p.length)return null;const unseen=p.find(c=>state.stats[c.id].seen===0);if(unseen)return unseen;let t=p.reduce((n,c)=>n+weight(c),0),r=Math.random()*t;for(const c of p){r-=weight(c);if(r<=0)return c}return p[p.length-1]}
function current(){return GREEK_CARDS.find(c=>c.id===state.current)||pick()}
function escape(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
export async function mountGreek(el){root=el;state=norm(await loadProgress(DECK,fresh));if(!state.current||!GREEK_CARDS.some(c=>c.id===state.current))state.current=pick()?.id;renderShell();render();}
function renderShell(){root.innerHTML=`<div class="deck-header"><div><p class="eyebrow">Greek I</p><h1>Alphabet, punctuation & accents</h1><div class="deck-subtitle">55 adaptive flashcards. Uppercase and lowercase letters are separate cards.</div></div><div class="deck-tools"><select id="gFilter"><option value="all">All 55 cards</option><option value="Alphabet — uppercase">Uppercase alphabet</option><option value="Alphabet — lowercase">Lowercase alphabet</option><option value="Punctuation">Punctuation</option><option value="Accent marks">Accent marks</option></select><button class="btn secondary" id="gReset">Reset Greek</button></div></div><div class="stats-grid"><div class="stat"><span>Answered</span><strong id="gAnswered">0</strong></div><div class="stat"><span>Accuracy</span><strong id="gAccuracy">—</strong></div><div class="stat"><span>Cards seen</span><strong id="gSeen">0 / 55</strong></div><div class="stat"><span>Wrong / hard</span><strong id="gWeak">0</strong></div></div><div class="deck-shell"><div class="card-meta"><span id="gCategory"></span><span id="gSeenLabel"></span></div><button class="flashcard" id="gCard"><span class="side" id="gSide">Front</span><span class="front greek" id="gFront"></span><div id="gAnswer" class="answer hidden"><div class="answer-title" id="gTitle"></div><div id="gBack"></div></div></button><div class="controls" id="gFrontControls"><button class="btn primary" id="gReveal">Reveal answer</button></div><div id="gBackControls" class="hidden"><div class="rating-grid"><div class="rating-group"><h3>Did you get it right?</h3><div class="choice-row"><button class="choice" data-g-result="right">Right</button><button class="choice" data-g-result="wrong">Wrong</button></div></div><div class="rating-group"><h3>How difficult was it?</h3><div class="choice-row"><button class="choice" data-g-diff="easy">Easy</button><button class="choice" data-g-diff="medium">Medium</button><button class="choice" data-g-diff="hard">Hard</button></div></div></div><button class="btn primary save-next" id="gNext" disabled>Save & next card</button></div></div><div class="priority"><h2>Priority review</h2><div class="chips" id="gPriority"></div><div class="source-note">Wrong and Hard cards return more often. Easy + Right cards remain in periodic review.</div></div>`;
root.querySelector('#gFilter').value=state.filter||'all';root.querySelector('#gFilter').addEventListener('change',async e=>{state.filter=e.target.value;state.current=pick()?.id;await saveProgress(DECK,state);render()});root.querySelector('#gCard').addEventListener('click',reveal);root.querySelector('#gReveal').addEventListener('click',reveal);root.querySelectorAll('[data-g-result]').forEach(b=>b.addEventListener('click',()=>{result=b.dataset.gResult;choices()}));root.querySelectorAll('[data-g-diff]').forEach(b=>b.addEventListener('click',()=>{diff=b.dataset.gDiff;choices()}));root.querySelector('#gNext').addEventListener('click',commit);root.querySelector('#gReset').addEventListener('click',async()=>{if(!confirm('Reset all Greek progress?'))return;state=fresh();state.current=pick()?.id;await saveProgress(DECK,state);render()});}
function reveal(){if(revealed)return;revealed=true;root.querySelector('#gSide').textContent='Back';root.querySelector('#gAnswer').classList.remove('hidden');root.querySelector('#gFrontControls').classList.add('hidden');root.querySelector('#gBackControls').classList.remove('hidden')}
function choices(){root.querySelectorAll('[data-g-result]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.gResult===result)));root.querySelectorAll('[data-g-diff]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.gDiff===diff)));root.querySelector('#gNext').disabled=!(result&&diff)}
async function commit(){if(!result||!diff)return;const c=current(),s=state.stats[c.id];s.seen++;s[result]++;s[diff]++;s.last=state.answered;state.answered++;state.history.push([Date.now(),c.id,result,diff]);state.history=state.history.slice(-1500);state.current=pick()?.id;await saveProgress(DECK,state);render()}
function render(){const c=current();if(!c)return;state.current=c.id;revealed=false;result=null;diff=null;root.querySelector('#gFront').textContent=c.front;root.querySelector('#gTitle').textContent=c.back_title;root.querySelector('#gBack').textContent=c.back;root.querySelector('#gCategory').textContent=c.category;const s=state.stats[c.id];root.querySelector('#gSeenLabel').textContent=`Seen ${s.seen} ${s.seen===1?'time':'times'}`;root.querySelector('#gSide').textContent='Front';root.querySelector('#gAnswer').classList.add('hidden');root.querySelector('#gFrontControls').classList.remove('hidden');root.querySelector('#gBackControls').classList.add('hidden');root.querySelector('#gNext').disabled=true;root.querySelectorAll('.choice').forEach(b=>b.setAttribute('aria-pressed','false'));stats()}
function stats(){const vals=Object.values(state.stats),r=vals.reduce((n,s)=>n+s.right,0),w=vals.reduce((n,s)=>n+s.wrong,0);root.querySelector('#gAnswered').textContent=state.answered;root.querySelector('#gAccuracy').textContent=state.answered?Math.round(r/Math.max(1,r+w)*100)+'%':'—';root.querySelector('#gSeen').textContent=vals.filter(s=>s.seen>0).length+' / 55';root.querySelector('#gWeak').textContent=vals.filter(s=>s.wrong>0||s.hard>0).length;const arr=GREEK_CARDS.map(c=>({c,s:state.stats[c.id],w:weight(c)})).filter(x=>x.s.seen>0&&(x.s.wrong>0||x.s.hard>0)).sort((a,b)=>b.w-a.w).slice(0,8),box=root.querySelector('#gPriority');box.innerHTML=arr.length?arr.map(x=>`<span class="chip">${escape(x.c.front)} · ${x.s.wrong} wrong · ${x.s.hard} hard</span>`).join(''):'<span class="source-note">No priority cards yet.</span>'}
