import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { loadGreekDeck } from "../data/builtin-decks";
import { useAuth } from "../features/auth/auth-context";
import { StudySession } from "../features/study/study-session";
import type { StudyDirection } from "../features/study/types";
import { useAsync } from "../hooks/use-async";
const filters = [["all", "All 55 cards"], ["Alphabet — uppercase", "Uppercase"], ["Alphabet — lowercase", "Lowercase"], ["Punctuation", "Punctuation"], ["Accent marks", "Accent marks"]] as const;
export function GreekPage() { const { value: deck, error } = useAsync(loadGreekDeck, []), { user } = useAuth(), [direction, setDirection] = useState<StudyDirection>("forward"), [filter, setFilter] = useState("all"); const cards = useMemo(() => deck?.cards.filter((card) => filter === "all" || card.category === filter) ?? [], [deck, filter]); return <main className="page-shell study-page"><div className="study-page-heading"><div><p className="eyebrow">Alphabet · punctuation · accents</p><h1>Greek I</h1></div><p>55 adaptive flashcards · separate progress in both directions</p></div>{!user && <div className="guest-banner"><span>You are studying as a guest. Progress stays on this device.</span><Link to="/account">Sign in to sync</Link></div>}{error && <div className="inline-alert">{error}</div>}{deck ? <StudySession deck={deck} cards={cards} studyKey={direction} direction={direction} onDirectionChange={setDirection} directionLabels={{ forward: "Symbol → Name", reverse: "Name → Symbol" }} toolbarExtra={<label className="compact-select-label"><span className="sr-only">Greek card category</span><select value={filter} onChange={(event) => setFilter(event.target.value)}>{filters.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>} cardMeta={(card) => `Card ${card.rank ?? 0} of 55`} renderFront={(_card, copy) => <span className={direction === "forward" ? "greek-front" : "study-prompt reverse-text-prompt"}>{copy.prompt}</span>} renderBack={(card) => { const details = direction === "forward" ? card.back.split("\n").slice(1).join("\n") : card.reverseBack?.split("\n").slice(1).join("\n"); return <span className="answer-block"><strong className={direction === "reverse" ? "greek-front compact-greek" : "greek-answer-title"}>{direction === "reverse" ? card.front : String(card.metadata?.backTitle ?? "Answer")}</strong><span className="answer-notes">{details}</span></span>; }} /> : <div className="study-loading panel-surface"><span className="loading-mark">α</span><p>Preparing Greek I…</p></div>}</main>; }
