import { useMemo, useState } from "react";
import { HenleChartTable } from "../features/henle/henle-chart";
import { loadHenle, type HenleChart } from "../features/henle/henle-data";
import { StudySession } from "../features/study/study-session";
import type { StudyCard, StudyDirection } from "../features/study/types";
import { useAsync } from "../hooks/use-async";
type Format = "individual" | "charts";
const scopes = [["all", "All Part I forms"], ["section:Nouns", "Nouns"], ["section:Adjectives", "Adjectives"], ["section:Adverbs", "Adverbs"], ["section:Numerals", "Numerals"], ["section:Pronouns", "Pronouns"], ["section:Verbs", "All Verbs"], ["voice:Active Voice", "Active Voice"], ["voice:Passive Voice", "Passive Voice"], ["sub:Verb Foundations & Principal Parts", "Verb Foundations & Principal Parts"], ["sub:Regular Verbs — Active Voice", "Regular Verbs — Active Voice"], ["sub:Regular Verbs — Passive Voice", "Regular Verbs — Passive Voice"], ["sub:Third Conjugation -iō — Active Voice", "Third Conjugation -iō — Active Voice"], ["sub:Third Conjugation -iō — Passive Voice", "Third Conjugation -iō — Passive Voice"], ["sub:Deponent Verbs", "Deponent Verbs"], ["sub:Semi-Deponent Verbs", "Semi-Deponent Verbs"], ["sub:Irregular Verbs", "Irregular Verbs"], ["sub:Defective Verbs", "Defective Verbs"], ["sub:Participles — Declension", "Participles — Declension"]] as const;
function matches(card: StudyCard, scope: string) { if (scope === "all") return true; const section = card.category ?? "", sub = String(card.metadata?.studySubsection ?? ""), voice = String(card.metadata?.voiceGroup ?? ""); if (scope.startsWith("section:")) return section === scope.slice(8); if (scope.startsWith("voice:")) return section === "Verbs" && voice === scope.slice(6); if (scope.startsWith("sub:")) return section === "Verbs" && sub === scope.slice(4); return true; }
export function HenlePage() {
  const { value: henle, error } = useAsync(loadHenle, []), [format, setFormat] = useState<Format>("individual"), [direction, setDirection] = useState<StudyDirection>("forward"), [scope, setScope] = useState("all"), [rule, setRule] = useState("");
  const deck = format === "charts" ? henle?.chartDeck : henle?.individualDeck, cards = useMemo(() => deck?.cards.filter((card) => matches(card, scope) && (!rule.trim() || Number(card.metadata?.rule ?? card.rank) === Number(rule))) ?? [], [deck, rule, scope]); const studyKey = format === "charts" ? "chart" : `individual:${direction}`;
  return <main className="page-shell study-page henle-page"><div className="study-page-heading"><div><p className="eyebrow">Part I · complete forms deck</p><h1>Henle Latin Grammar</h1></div><p>2,062 forms · 331 rules · 248 whole charts</p></div><div className="henle-format-bar panel-surface"><label><span>Study format</span><select value={format} onChange={(event) => setFormat(event.target.value as Format)}><option value="individual">Individual Forms</option><option value="charts">Whole Charts</option></select></label><label><span>Category</span><select value={scope} onChange={(event) => setScope(event.target.value)}>{scopes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Henle rule</span><input inputMode="numeric" value={rule} onChange={(event) => setRule(event.target.value.replace(/\D/g, ""))} placeholder="e.g. 138" /></label></div>{error && <div className="inline-alert">{error}</div>}{deck ? <StudySession key={format} deck={deck} cards={cards} studyKey={studyKey} direction={format === "charts" ? "forward" : direction} onDirectionChange={format === "individual" ? setDirection : undefined} directionLabels={{ forward: "Prompt → Form", reverse: "Form → Identify" }} cardMeta={(card) => `${String(card.metadata?.studySubsection ?? "") ? `${String(card.metadata?.studySubsection)} · ` : ""}Rule ${card.rank}`} priorityPrompt={(card, copy) => format === "charts" ? `${card.front} · Complete chart` : copy.prompt} renderFront={(card, copy) => { if (format === "charts") { const chart = card.metadata?.chart as HenleChart; return <span className="henle-chart-face"><strong className="henle-card-title">{chart.title}</strong><span className="chart-instruction">Reconstruct the complete chart from memory.</span><HenleChartTable items={chart.items} revealed={false} /></span>; } return direction === "forward" ? <span className="henle-card-copy"><strong className="henle-card-title">{String(card.metadata?.title ?? "")}</strong><span className="henle-prompt">{String(card.metadata?.prompt ?? copy.prompt)}</span></span> : <span className="henle-prompt henle-form-prompt">{copy.prompt}</span>; }} renderBack={(card, copy) => { if (format === "charts") { const chart = card.metadata?.chart as HenleChart; return <span className="henle-chart-face"><strong className="henle-card-title">{chart.title}</strong><HenleChartTable items={chart.items} revealed /></span>; } return <span className="answer-block henle-answer-block"><strong className="henle-answer">{copy.answer}</strong><span className="answer-notes">Rule {card.rank}</span></span>; }} /> : <div className="study-loading panel-surface"><span className="loading-mark">H</span><p>Loading all 2,062 Henle cards…</p></div>}</main>;
}
