import { ArrowRight, BookOpenText, Cloud, Repeat2, TableProperties } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../features/auth/auth-context";
export function HomePage() { const { user } = useAuth(); return <main className="page-shell home-page">
  <section className="home-intro"><div><p className="eyebrow">Active recall · adaptive review</p><h1>Build a durable memory of Greek and Latin.</h1><p className="home-lede">Reveal each answer from memory, judge your response, and rate its difficulty. Every direction keeps its own history, and slower recall returns a card sooner.</p></div><div className="method-note"><Repeat2 /><div><strong>One deliberate cycle</strong><span>Recall · reveal · rate · review</span></div></div></section>
  <section className="course-grid"><Course glyph="Ἀ" count="55 cards" eyebrow="Greek I" title="Alphabet, punctuation, and accents" copy="Study symbols forward or recall each uppercase and lowercase form from its name." href="/greek" link="Study Greek" /><Course glyph="A" count="997 entries" eyebrow="Latin vocabulary" title="Dickinson Core Vocabulary" copy="Begin with the top 100, then unlock 25 at a time in each study direction." href="/latin" link="Study Latin" /><Course icon={<TableProperties />} count="2,062 forms" eyebrow="Henle Grammar" title="Individual forms and whole charts" copy="Study all 331 supplied rule groups, including 248 complete-chart exercises." href="/henle" link="Study grammar" /><Course icon={<BookOpenText />} count="Greek & Latin" eyebrow="Reading & Audio" title="Follow a passage word by word" copy="Save readings, attach audio, navigate sentences, and use timing-based highlighting." href="/reading" link="Open readings" /></section>
  <section className="sign-in-callout panel-surface"><div className="callout-icon"><Cloud /></div><div><h2>{user ? "Your progress is connected" : "Keep your place on every device"}</h2><p>{user ? "Forward, reverse, whole-chart, reading, and imported-deck progress can sync to your account." : "Guest study works immediately on this device. Sign in when cloud accounts are configured to sync everywhere."}</p></div><Link className="button-link primary-button" to="/account">{user ? "View account" : "Sign in to sync"}</Link></section>
  </main>; }
function Course({ glyph, icon, count, eyebrow, title, copy, href, link }: { glyph?: string; icon?: React.ReactNode; count: string; eyebrow: string; title: string; copy: string; href: string; link: string }) { return <article className="course-card"><div className="course-card-top">{glyph ? <span className="course-glyph">{glyph}</span> : <span className="course-icon">{icon}</span>}<span className="course-count">{count}</span></div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p><Link className="course-link" to={href}>{link} <ArrowRight /></Link></article>; }
