import readXlsxFile from "read-excel-file";
import { parseCsv } from "../../data/builtin-decks";
import type { ImportCard } from "./deck-service";

const normalizeHeader = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/[_-]+/g, " ").replace(/\s+/g, " ");
export function rowsToCards(rows: unknown[][]) {
  if (rows.length < 2) throw new Error("The import file has no card rows."); const headers = rows[0].map(normalizeHeader), column = (...names: string[]) => headers.findIndex((header) => names.includes(header));
  const front = column("front", "question", "prompt"), back = column("back", "answer", "definition"); if (front < 0 || back < 0) throw new Error("Imports require Front and Back columns.");
  const category = column("category"), rank = column("rank", "frequency rank"), source = column("source"), notes = column("notes", "note"), reversePrompt = column("reverse prompt", "reverse");
  return rows.slice(1).map((row) => ({ front: String(row[front] ?? "").trim(), back: String(row[back] ?? "").trim(), category: category >= 0 ? String(row[category] ?? "").trim() : "", rank: rank >= 0 && String(row[rank] ?? "").trim() ? Number(row[rank]) : null, source: source >= 0 ? String(row[source] ?? "").trim() : "", notes: notes >= 0 ? String(row[notes] ?? "").trim() : "", reversePrompt: reversePrompt >= 0 ? String(row[reversePrompt] ?? "").trim() : "" })).filter((card) => card.front && card.back).map((card, index) => ({ ...card, rank: Number.isFinite(card.rank) ? card.rank : index + 1 })) satisfies ImportCard[];
}
export function jsonToCards(value: unknown) { const source = Array.isArray(value) ? value : value && typeof value === "object" && Array.isArray((value as { cards?: unknown[] }).cards) ? (value as { cards: unknown[] }).cards : null; if (!source) throw new Error("JSON must be an array of cards or an object with a cards array."); return source.map((item, index) => { const card = item as Record<string, unknown>; return { front: String(card.Front ?? card.front ?? card.prompt ?? "").trim(), back: String(card.Back ?? card.back ?? card.answer ?? "").trim(), category: String(card.Category ?? card.category ?? "").trim(), rank: Number(card.Rank ?? card.rank ?? index + 1), source: String(card.Source ?? card.source ?? "").trim(), notes: String(card.Notes ?? card.notes ?? card.note ?? "").trim(), reversePrompt: String(card["Reverse Prompt"] ?? card.reversePrompt ?? card.reverse_prompt ?? "").trim() }; }).filter((card) => card.front && card.back) satisfies ImportCard[]; }
export async function parseDeckImport(file: File) { const extension = file.name.split(".").at(-1)?.toLowerCase(); let cards: ImportCard[]; if (extension === "json") cards = jsonToCards(JSON.parse(await file.text())); else if (extension === "xlsx" || extension === "xls") cards = rowsToCards((await readXlsxFile(file)) as unknown[][]); else cards = rowsToCards(parseCsv(await file.text())); if (!cards.length) throw new Error("No valid cards were found in the import."); return cards; }
